<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>StruggleGame.Launcher</RootNamespace>
    <AssemblyName>StruggleGameLauncher</AssemblyName>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <SelfContained>false</SelfContained>
    <DebugType>embedded</DebugType>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
